#!/usr/bin/env python3
"""Build CS6650 HW10 Word report from AWS summaries and results/aws/figs PNGs.

  pip install python-docx
  python3 scripts/build_hw10_report_docx.py

Output: CS6650_HW10_Report.docx in repo root (override with -o).
"""
from __future__ import annotations

import argparse
import glob
import os
import sys

try:
    from docx import Document
    from docx.shared import Inches, Pt
except ImportError:
    print("Install: pip install python-docx", file=sys.stderr)
    sys.exit(1)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "-o",
        "--output",
        default="CS6650_HW10_Report.docx",
        help="output filename in repo root unless absolute path",
    )
    ap.add_argument("--figs", default="results/aws/figs", help="PNG directory under repo root")
    args = ap.parse_args()

    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    os.chdir(root)

    summary_path = os.path.join(root, "results/aws/AWS_RUN_SUMMARY.txt")
    snippets_path = os.path.join(root, "results/aws/WRITEUP_SNIPPETS.txt")
    out_path = args.output if os.path.isabs(args.output) else os.path.join(root, args.output)
    figs_dir = args.figs if os.path.isabs(args.figs) else os.path.join(root, args.figs)

    doc = Document()
    h0 = doc.add_heading("CS 6650 — Homework 10", 0)
    if h0.runs:
        h0.runs[0].font.size = Pt(22)
    doc.add_heading("Replicated key–value stores (Leader–Follower & Leaderless)", level=1)

    doc.add_paragraph(
        "AI / tooling disclosure: Implementation, infrastructure (Docker, Terraform, ECR/EC2), "
        "load-test automation, plotting, and this report document were produced with assistance from "
        "an AI coding agent. All measurements below were produced by running the provided load tests "
        "against your deployed cluster; align wording with the instructor’s disclosure policy."
    )

    doc.add_heading("Experimental setup & raw summary", level=2)
    if os.path.isfile(summary_path):
        doc.add_paragraph(open(summary_path, encoding="utf-8").read().strip())
    else:
        doc.add_paragraph("(Add results/aws/AWS_RUN_SUMMARY.txt after cloud runs.)")

    doc.add_heading("Analysis (edit as needed)", level=2)
    if os.path.isfile(snippets_path):
        body = open(snippets_path, encoding="utf-8").read()
        # Skip first line ("Paste or adapt...")
        lines = body.splitlines()
        start = 1 if lines and lines[0].lower().startswith("paste") else 0
        for raw_line in lines[start:]:
            line = raw_line.rstrip()
            if not line.strip():
                continue
            sec_heads = {
                "Setup (one sentence)",
                "Throughput vs write fraction (leader–follower)",
                "Staleness",
                "Figures",
            }
            if line in sec_heads:
                doc.add_heading(line, level=3)
                continue
            if line.startswith("- "):
                doc.add_paragraph(line[2:], style="List Bullet")
            else:
                doc.add_paragraph(line)

    doc.add_heading("Histograms (AWS, 50s × 8 workers)", level=2)
    doc.add_paragraph(
        "Generated by scripts/plot_loadtest.py via scripts/plot_results_dir.sh. "
        "Each file: read latency, write latency, time since last write to same key."
    )

    pattern = os.path.join(figs_dir, "*.png")
    paths = sorted(glob.glob(pattern))
    if not paths:
        doc.add_paragraph(f"(No PNGs found in {figs_dir} — run plot_results_dir.sh first.)")
    pic_width = Inches(6)
    for png in paths:
        doc.add_paragraph(os.path.basename(png), style="Intense Quote")
        doc.add_picture(png, width=pic_width)

    doc.save(out_path)
    print(out_path, file=sys.stderr)


if __name__ == "__main__":
    main()
